### ISSUE TITLE
[demo ] Feature flag service is failing to start

### ISSUE THREAD

**Issue by dineshg13** [open-telemetry/opentelemetry-helm-charts#343]
When we run the latest demo chart application via command 

```
helm install mydemo ./opentelemetry-demo
```
we see Feature flag service is failing to start . 
```
k logs mydemo-featureflag-service-5d59b6cfb7-tl5mc                                                                                                                                                         ─╯
ERROR! Config provider Config.Reader failed with:
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not a binary

    :erlang.binary_to_integer(nil)
    (stdlib 4.0) erl_eval.erl:744: :erl_eval.do_apply/7
    (stdlib 4.0) erl_eval.erl:492: :erl_eval.expr/6
    (elixir 1.13.3) src/elixir.erl:296: :elixir.recur_eval/3
    (elixir 1.13.3) src/elixir.erl:274: :elixir.eval_forms/3
    (elixir 1.13.3) lib/code.ex:404: Code.validated_eval_string/3
    (elixir 1.13.3) lib/config.ex:260: Config.__eval__!/3
    (elixir 1.13.3) lib/config/reader.ex:92: Config.Reader.read!/2

{"init terminating in do_boot",{badarg,[{erlang,binary_to_integer,[nil],[{error_info,#{module=>erl_erts_errors}}]},{erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,744}]},{erl_eval,expr,6,[{file,"erl_eval.erl"},{line,492}]},{elixir,recur_eval,3,[{file,"src/elixir.erl"},{line,296}]},{elixir,eval_forms,3,[{file,"src/elixir.erl"},{line,274}]},{'Elixir.Code',validated_eval_string,3,[{file,"lib/code.ex"},{line,404}]},{'Elixir.Config','__eval__!',3,[{file,"lib/config.ex"},{line,260}]},{'Elixir.Config.Reader','read!',2,[{file,"lib/config/reader.ex"},{line,92}]}]}}
init terminating in do_boot ({badarg,[{erlang,binary_to_integer,[nil],[{_}]},{erl_eval,do_apply,7,[{_},{_}]},{erl_eval,expr,6,[{_},{_}]},{elixir,recur_eval,3,[{_},{_}]},{elixir,eval_forms,3,[{_},{_}]},{Elixir.Code,validated_eval_string,3,[{_},{_}]},{Elixir.Config,__eval__!,3,[{_},{_}]},{Elixir.Config.Reader,read!,2,[{_},{_}]}]})

Crash dump is being written to: erl_crash.dump...done
ERROR! Config provider Config.Reader failed with:
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not a binary

    :erlang.binary_to_integer(nil)
    (stdlib 4.0) erl_eval.erl:744: :erl_eval.do_apply/7
    (stdlib 4.0) erl_eval.erl:492: :erl_eval.expr/6
    (elixir 1.13.3) src/elixir.erl:296: :elixir.recur_eval/3
    (elixir 1.13.3) src/elixir.erl:274: :elixir.eval_forms/3
    (elixir 1.13.3) lib/code.ex:404: Code.validated_eval_string/3
    (elixir 1.13.3) lib/config.ex:260: Config.__eval__!/3
    (elixir 1.13.3) lib/config/reader.ex:92: Config.Reader.read!/2

{"init terminating in do_boot",{badarg,[{erlang,binary_to_integer,[nil],[{error_info,#{module=>erl_erts_errors}}]},{erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,744}]},{erl_eval,expr,6,[{file,"erl_eval.erl"},{line,492}]},{elixir,recur_eva=ERROR REPORT==== 25-Aug-2022::14:20:33.872502 ===
Error in process <0.9.0> on node 'featureflagservice@mydemo-featureflag-service-5d59b6cfb7-tl5mc' with exit value:
{badarg,[{erlang,binary_to_integer,
```

**Comment by TylerHelmuth** [comment]
@dineshg13 I am able to start the chart without any issues:

```bash
thelmuth@Y00L6P6JJF opentelemetry-helm-charts % kubectl get pods
NAME                                              READY   STATUS    RESTARTS   AGE
mydemo-ad-service-746bff5466-82xqp                1/1     Running   0          4m19s
mydemo-cart-service-c6c8566b8-gwwd9               1/1     Running   0          4m18s
mydemo-checkout-service-59648cd69d-bflv7          1/1     Running   0          4m19s
mydemo-currency-service-fd596f466-xdh7k           1/1     Running   0          4m19s
mydemo-email-service-66c5b6479c-p9wtl             1/1     Running   0          4m19s
mydemo-featureflag-service-db494b8dc-tsdwn        1/1     Running   0          4m18s
mydemo-ffs-postgres-b4d8b89d-vnm87                1/1     Running   0          4m18s
mydemo-frontend-c58bcbcff-wxh5m                   1/1     Running   0          4m18s
mydemo-jaeger-7cb5c584d-sx4zq                     1/1     Running   0          4m18s
mydemo-loadgenerator-56fb7f484c-wkjkc             1/1     Running   0          4m19s
mydemo-otelcol-5f8698c8bd-6b57d                   1/1     Running   0          4m17s
mydemo-payment-service-779c4cb8bd-rtshp           1/1     Running   0          4m18s
mydemo-product-catalog-service-669594cc54-nt9lf   1/1     Running   0          4m18s
mydemo-recommendation-service-67576c6b5-plwrc     1/1     Running   0          4m19s
mydemo-redis-74657489b6-pszp6                     1/1     Running   0          4m18s
mydemo-shipping-service-7dcd8cd7d6-s489v          1/1     Running   0          4m19s
```

Can you provide some more details like what helm and k8s version you are using?  Also, are you installed from `helm repo add` or from a local instance of the chart?

**Comment by TylerHelmuth** [comment]
I was just able to reproduce this issue in a K8s 1.22.10-gke.600 cluster.  The above is in a k8s 1.24.0 cluster.

**Comment by dineshg13** [comment]
@TylerHelmuth interesting. am getting an error , both on my local docker kubernetes and EKS cluster. 
EKS versions 
```
Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.22.11-eks-18ef993
```

**Comment by dineshg13** [comment]
sorry .. i didn't see ur comment that u were able to reproduce

**Comment by TylerHelmuth** [comment]
@dineshg13 can you try on 1.23?  Also very curious if you are able to deploy the demo on 1.22 without the helm chart.  I have a suspicion that this isn't a helm issue.

**Comment by TylerHelmuth** [comment]
Was able to reproduce on k8s 1.23.7-gke.1400

**Comment by TylerHelmuth** [comment]
I was also able to reproduce the error in 1.24.2-gke.1900 but the contain does eventually start.  

@dineshg13 investigating this issue further is gonna take some knowledge of the actually demo code since `featureflag-service` is the thing actually erroring.  Are you able to head up the investigation?

**Comment by joshleecreates** [comment]
I think the error is originating [here](https://github.com/open-telemetry/opentelemetry-demo/blob/379ee4fc127f6dd704a7e6072f323ec904d1daa6/src/featureflagservice/config/runtime.exs#L7) because of missing environment variables. I am able to recreate the same error by running the phoenix application directly (without Docker) and without loading the `.env` from the project root directory. I don't have enough context to say why this is happening specifically in some k8s situations and not others.

**Comment by TylerHelmuth** [comment]
@joshleecreates thanks for the investigation. Do you want to submit a PR to add this env variable to the chart? I believe it is being added for the product catalog service already.

**Comment by joshleecreates** [comment]
Sure I can do that.
