### ISSUE TITLE
[opentelemetry collector] logCollection preset multiline logs

### ISSUE THREAD

**Issue by povilasv** [open-telemetry/opentelemetry-helm-charts#809]
I would like to work on some kind of support for multi-line logs for log collection.

Currently I have two ideas:

1) Some runtimes like CRI, have a marker to indicate continuation of log line. See example in recombine operator 

![image](https://github.com/open-telemetry/opentelemetry-helm-charts/assets/22289110/17f183a9-4138-4943-9608-4617f3d3e502)

So for CRI we could add this:
```
- type: regex_parser
  regex: '^(?P<timestamp>[^\s]+) (?P<stream>\w+) (?P<logtag>\w) (?P<message>.*)'
- type: recombine
  combine_field: body.message
  combine_with: ""
  is_last_entry: "body.logtag == 'F'"
  overwrite_with: "newest"
```

That's one idea.

2) Another idea came from this - I've played with some app that sends multline configs and with containerd I see:
```
2023-06-08T12:29:28.123760947Z stderr F goroutine 17 [finalizer wait]:
2023-06-08T12:29:28.12378603Z stderr F runtime.gopark(0x40000345a8?, 0x600000000224a8?, 0xa8?, 0xd0?, 0x1?)
2023-06-08T12:29:28.123805571Z stderr F         /usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x4000034580 sp=0x4000034560 pc=0x422e0
2023-06-08T12:29:28.123824237Z stderr F runtime.runfinq()
2023-06-08T12:29:28.123842029Z stderr F         /usr/local/go/src/runtime/mfinal.go:193 +0x100 fp=0x40000347d0 sp=0x4000034580 pc=0x23af0
2023-06-08T12:29:28.123859236Z stderr F runtime.goexit()
2023-06-08T12:29:28.123876736Z stderr F         /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40000347d0 sp=0x40000347d0 pc=0x6dba4
2023-06-08T12:29:28.123893944Z stderr F created by runtime.createfing
2023-06-08T12:29:28.123911444Z stderr F         /usr/local/go/src/runtime/mfinal.go:163 +0x80
2023-06-08T12:29:28.123927777Z stderr F
```

All lines marked as single line entries. Which means that 1) idea wouldn't help in my case.

So what I'm thinking is to have an option to configure router and recombine operator to recombine certain logs?

The best example of this is java Exception from [recombine operator examples](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/operators/recombine.md#recombine-stack-traces-into-multiline-logs)

![image](https://github.com/open-telemetry/opentelemetry-helm-charts/assets/22289110/b0f8a668-d780-4381-8749-50f4a66dd8aa)

**Comment by TylerHelmuth** [comment]
If there is a commonly used log format that shows up in k8s that our default operators isn't handling I would support adding support for that format.  In that case we should also update the [collector k8s example](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/examples/kubernetes).

**Comment by TylerHelmuth** [comment]
The presets shouldn't allow complex configuration in the values.yaml, but they can handle complex, but default, scenarios OOTB.  It's actually really great for the presets to handle something complex, as long as it is common.
